[package]
name = "docker-back"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.18"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"